version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Amiga/aMiLa/mcp-server-vamigaweb"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directory: "/Hardware/Flume/flume-dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directory: "/Hardware/SensorTag"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directory: "/Hardware/sleepia"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
