[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "joe-controller"
version = "0.1.0"
description = "A direct controller for the Huenit robotic arm."
requires-python = ">=3.9"
dependencies = [
    "pynput",
    "pyserial",
    "numpy",
    "opencv-python",
    "ultralytics",
]

[tool.setuptools.packages.find]
include = ["joe_controller"]
exclude = ["external", "external.*"]
