baseURL = '/'
title = 'Back to Amiga Dev Hub'
defaultContentLanguage = 'en'
publishDir = 'public'
uglyURLs = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
