= Analay

**Description**: Math and Layout Software

	**Technology stack**: Modula-2

For more history see it's webpage - - https://web.archive.org/web/20180910182808/http://analay.marcnecker.de/

_Analay is an analysis program. It provides all the standard features
such a math program needs, like creating the derivatives of functions,
calculating areas between functions, hatching areas, analysis of function
graphs, tables, lists, ... .
The special feature of this program is its integrated Layout Mode which
offers a small but complete DTP-program with full WYSIWYG and
Intellifont support. It allows you to layout a page with function graphs,
tables, lists, textblocks, etc. Analay also knows formulas which are entered
using the TeX-format. The whole page can be printed in highest printer
resolution._


== Dependencies

  * Amiga OS Classic
  * Modula-2 compatible compiler
  ....

== Build

..TO-DO

== Installation

  * TO-DO

== Getting help

If you have questions, concerns, bug reports, etc, please file an issue in this repository's Issue Tracker.

== Getting involved

Contact your old amiga friends and tell them about our project, and ask them to dig out their source code or floppies and send them to us for preservation.

Clean up our hosted archives, and make the source code buildable with standard compilers like devpac, asmone, gcc 2.9x/Beppo 6.x, sas/c ,vbcc and friends.


Cheers!

....

     _____ ___   _   __  __     _   __  __ ___ ___   _   
    |_   _| __| /_\ |  \/  |   /_\ |  \/  |_ _/ __| /_\  
      | | | _| / _ \| |\/| |  / _ \| |\/| || | (_ |/ _ \ 
     _|_| |___/_/ \_\_|_ |_|_/_/_\_\_|__|_|___\___/_/_\_\
    / __|/ _ \| | | | _ \/ __| __|  / __/ _ \|   \| __|  
    \__ \ (_) | |_| |   / (__| _|  | (_| (_) | |) | _|   
    |___/\___/_\___/|_|_\\___|___|__\___\___/|___/|___|_ 
    | _ \ _ \ __/ __| __| _ \ \ / /_\_   _|_ _/ _ \| \| |
    |  _/   / _|\__ \ _||   /\ V / _ \| |  | | (_) | .` |
    |_| |_|_\___|___/___|_|_\ \_/_/ \_\_| |___\___/|_|\_|

....

https://twitter.com/AmigaSourcePres[Twitter]
https://gitlab.com/amigasourcecodepreservation[Gitlab] 
https://amigasourcepres.gitlab.io/[WWW]

== License

Analay is distributed under the terms of the GPL v2 License. See the https://gitlab.com/amigasourcecodepreservation/analay/LICENSE[LICENSE] file for details.

== Credits and references

Many thanks to Marc Necker for the source code and for telling the story behind it.

