*************************************************************************
*									*
*     Macintosh to AmigaDOS file conversion utility.			*
*									*
*	Copyright (c) 1988 Central Coast Software			*
*	    268 Bowie Dr, Los Osos, CA 93402				*
*	     All rights reserved, worldwide				*
*									*
*************************************************************************

;	INCLUDE "I/MACROS.ASM"
;	INCLUDE "I/EQUATES.ASM"
	INCLUDE	"I/MACMAC.ASM"

* HARDWARE REGISTER DEFINITIONS

DSKPTR	EQU	$DFF020
DSKLEN	EQU	$DFF024
DSKBYTR	EQU	$DFF01A
DSKSYNC	EQU	$DFF07E
CIAA	EQU	$BFE001
CIAB	EQU	$BFD100
INTENAR	EQU	$DFF01C
INTENA	EQU	$DFF09A
INTREQ	EQU	$DFF09C
INTREQR	EQU	$DFF01E
ADKCON	EQU	$DFF09E
ADKCONR	EQU	$DFF010
VHPOSR	EQU	$DFF006

TR_ADDREQUEST	EQU	9	;TIMER IO REQUEST

DF0		EQU	$08
NONE		EQU	DF0
CA0		EQU	$80+DF0
CA1		EQU	$01+DF0
CA2		EQU	$02+DF0
DrvEnable	EQU	$20+DF0
LSTRB		EQU	$10+DF0
SEL		EQU	$04+DF0

BufferSize	EQU	20000

GO:
	MOVE.L  A7,initialSP		;initial task stack pointer
	MOVEA.L 4,A6
	MOVE.L  A6,SysBase
	LEA     DosName,A1
	ZAP	D0
	CALLSYS	OpenLibrary		;OPEN DOS LIBRARY
	MOVE.L  D0,LIBRARY_BASE
	ZAPA	A1
	CALLSYS	FindTask
	MOVE.L	D0,D2D_TASK		;save ptr for msg ports
	MOVEA.L D0,A4
	MOVE.L	#BufferSize,D0		;GRAB A BUNCH
	MOVEQ	#2,D1			;SPECIFY CHIP MEMORY
	CALLSYS	AllocMem,SysBase	;GRAB A HUNK OF CHIP MEMORY
	MOVE.L	D0,BUFFER
	BEQ	ABORT
	LEA	DISK_NAME,A1		;SET UP POINTER TO DISK RESOURCE
	CALLSYS	OpenResource
	MOVE.L  D0,DR_BASE		;POINTER TO DISK RESOURCE BLOCK
	BEQ	ABORT			;DIDN'T FIND IT
	LEA	CIAB,A2
	BSR	BUSY_DRIVES
	BSR	RdyTest
9$:	BSR	FREE_DRIVES
	MOVE.L	BUFFER,A1
	MOVE.L	#BufferSize,D0
	CALLSYS	FreeMem,SysBase		;RETURN TO POOL
ABORT:	
	MOVE.L	initialSP,A7
	MOVE.L	SysBase,A6
	MOVE.L	LIBRARY_BASE,D0
	BEQ.S	1$
	MOVE.L	D0,A1
	CALLSYS	CloseLibrary
1$:	CLR.L	D0
	RTS			;BACK TO AMIGA-DOS


* SETS AMIGA-DOS DISK DRIVES BUSY FOR DURATION OF DISK OPERATION.

BUSY_DRIVES:
        PUSH    A0-A1
1$:     MOVE.L  DR_BASE,A6      ;ASK AMIGA-DOS POLITELY...
        LEA     DISK_BLOCK,A1
        MOVE.L  D2D_TASK,MP_TASK
        CALL    DR_GetUnit(A6)  ;...FOR THE DISK CONTROLLER
        TST.L   D0
        BNE     2$              ;GOT THE DISK
        LEA     MSG_PORT,A0
        CALLSYS	WaitPort,SysBase ;WILL SEND REPLY TO DRU PORT
        LEA     MSG_PORT,A0
        CALLSYS	GetMsg		;UNQUEUE REPLY
        BRA.S   1$              ;NOW TRY FOR IT AGAIN
2$:     POP     A0-A1
        RTS

* FREES AMIGA-DOS DISK DRIVES AFTER DISK OPERATION.

FREE_DRIVES:
        MOVE.L  DR_BASE,A6 
        CALL    DR_GiveUnit(A6) ;FREE THE DISK RESOURCE
        RTS 

RdyTest:
	MOVE.B	#-1,(A2)	;clear interface
	MOVE.B	#$F7,(A2)	;enable df0:
	NOP
	NOP
	MOVE.B	#-1,(A2)
	MOVE.B	#$7F,(A2)
	MOVE.B	#$77,(A2)
	NOP
	NOP
	BEQ.S	RdyTest
	RTS


DosName		DC.B	'dos.library',0
DISK_NAME	DC.B	'disk.resource',0

D2D_TASK	DC.L	0	;TASK POINTER
SysBase		DC.L	0
LIBRARY_BASE	DC.L	0

initialSP	DC.L	0
DR_BASE		DC.L	0	;DISK RESOURCE POINTER
BUFFER		DC.L	0
COUNT		DC.L	0
DutyCycle	DC.L	0
OnCycle		DC.L	0
OffCycle	DC.L	0
DIR		DC.B	0	;step direction
STATE		DC.B	0	;tach state
EndTest		DC.B	0

HDRBUF	DCB.B	16,0		;SECTOR HEADER
NEWHDR	DCB.B	16,0		;ENCODED DESIRED SECTOR HEADER

* DISK RESOURCE UNIT STRUCTURE

INT_STRUCT MACRO
        NODE 2,0,0
        DC.L    0
        DC.L    0
        ENDM

        CNOP  0,4

DISK_BLOCK
        NODE    5,0,0
DB_PORT DC.L    MSG_PORT
        DC.W    DB_MLEN
        INT_STRUCT
        INT_STRUCT
        INT_STRUCT
DB_MLEN EQU *-DISK_BLOCK

TIMER_BLOCK
	NODE	5,0,0
TB_PORT	DC.L	MSG_PORT
	DC.W	TB_MLEN
	DC.L	0,0		;DEV, UNIT
TB_CMD	DC.W	0,0		;COMMAND, FLAGS, ERROR
TB_SECS	DC.L	0		;SECONDS
TB_USEC	DC.L	0		;MICROSECONDS
	DC.L	0,0,0,0		;STANDARD IO REQ EXT
TB_MLEN	EQU *-TIMER_BLOCK

MSG_PORT:
        NODE    4,0,0
        DC.B    0       ;FLAGS=SIGNAL
        DC.B    8       ;SIGNAL 8
MP_TASK DC.L    0       ;MY TASK
MP_HEAD DC.L    MP_TAIL ;HEAD
MP_TAIL DC.L    0       ;TAIL
        DC.L    MP_HEAD ;TAIL PRED
        DC.B    5       ;TYPE
        DC.B    0       ;PAD


        END


