*
*  Source machine generated by GadToolsBox V2.0b
*  which is (c) Copyright 1991-1993 Jaba Development
*
*  GUI Designed by : Captain Bifat
*

    include 'exec/types.i'
    include 'intuition/intuition.i'
    include 'intuition/classes.i'
    include 'intuition/classusr.i'
    include 'intuition/imageclass.i'
    include 'intuition/gadgetclass.i'
    include 'libraries/gadtools.i'
    include 'graphics/displayinfo.i'
    include 'graphics/gfxbase.i'

    XREF    _GadToolsBase
    XREF    _IntuitionBase
    XREF    _GfxBase
    XREF    _SysBase

OpenScreenTagList    EQU    -612
OpenWindowTagList    EQU    -606
CloseScreen          EQU    -66
CloseWindow          EQU    -72
PrintIText           EQU    -216
LockPubScreen        EQU    -510
UnlockPubScreen      EQU    -516
SetMenuStrip         EQU    -264
ClearMenuStrip       EQU    -54
GetVisualInfoA       EQU    -126
FreeVisualInfo       EQU    -132
CreateContext        EQU    -114
CreateGadgetA        EQU    -30
GT_RefreshWindow     EQU    -84
FreeGadgets          EQU    -36
CreateMenusA         EQU    -48
LayoutMenusA         EQU    -66
FreeMenus            EQU    -54
OpenDiskFont         EQU    -30
CloseFont            EQU    -78
DrawBevelBoxA        EQU    -120
FreeClass            EQU    -714
NewObjectA           EQU    -636
DisposeObject        EQU    -642
TextLength           EQU    -54
CopyMem              EQU    -624
FindTagItem          EQU    -30
IntuiTextLength      EQU    -330
Forbid               EQU    -132
Permit               EQU    -138

GD_displaypic                          EQU    0
GD_Gadget10                            EQU    1
GD_autosavepal                         EQU    2
GD_confirmexit                         EQU    3
GD_iconify                             EQU    4
GD_cancel                              EQU    5
GD_save                                EQU    6
GD_use                                 EQU    7
GD_adjustpal                           EQU    8
GD_font                                EQU    9
GD_setscreen                           EQU    10
GD_setfont                             EQU    11
GD_overwrite                           EQU    12
GD_screen                              EQU    13

Project0_CNT    EQU    14

    XDEF    Scr
    XDEF    VisualInfo
    XDEF    Project0Wnd
    XDEF    Project0GList
    XDEF    Project0Gadgets
    XDEF    Project0Left
    XDEF    Project0Top
    XDEF    Project0Width
    XDEF    Project0Height

Scr:
    DC.L    0
VisualInfo:
    DC.L    0
Project0Wnd:
    DC.L    0
Project0GList:
    DC.L    0
Project0Gadgets:
    DCB.L    14,0
BufNewGad:
    DC.W    0,0,0,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0,0
TD:
    DC.L    TAG_DONE
NR:
    DC.L    GT_VisualInfo,$00000000,TAG_DONE
IR:
    DC.L    GT_VisualInfo,$00000000,GTBB_Recessed,1,TAG_DONE
Project0Left:
    DC.W    126
Project0Top:
    DC.W    62
Project0Width:
    DC.W    432
Project0Height:
    DC.W    135

Project0GTypes:
    DC.W    CHECKBOX_KIND
    DC.W    CHECKBOX_KIND
    DC.W    CHECKBOX_KIND
    DC.W    CHECKBOX_KIND
    DC.W    CYCLE_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    TEXT_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    CHECKBOX_KIND
    DC.W    CYCLE_KIND

Project0NGads:
    DC.W    25,26,26,11
    DC.L    displaypicText,0
    DC.W    GD_displaypic
    DC.L    PLACETEXT_RIGHT,0,0
    DC.W    25,38,26,11
    DC.L    Gadget10Text,0
    DC.W    GD_Gadget10
    DC.L    PLACETEXT_RIGHT,0,0
    DC.W    25,80,26,11
    DC.L    autosavepalText,0
    DC.W    GD_autosavepal
    DC.L    PLACETEXT_RIGHT,0,0
    DC.W    25,50,26,11
    DC.L    confirmexitText,0
    DC.W    GD_confirmexit
    DC.L    PLACETEXT_RIGHT,0,0
    DC.W    294,28,103,13
    DC.L    iconifyText,0
    DC.W    GD_iconify
    DC.L    PLACETEXT_LEFT,0,0
    DC.W    306,112,92,14
    DC.L    cancelText,0
    DC.W    GD_cancel
    DC.L    PLACETEXT_IN,0,0
    DC.W    25,111,92,14
    DC.L    saveText,0
    DC.W    GD_save
    DC.L    PLACETEXT_IN,0,0
    DC.W    165,112,92,14
    DC.L    useText,0
    DC.W    GD_use
    DC.L    PLACETEXT_IN,0,0
    DC.W    207,79,191,13
    DC.L    adjustpalText,0
    DC.W    GD_adjustpal
    DC.L    PLACETEXT_IN,0,0
    DC.W    206,43,134,13
    DC.L    0,0
    DC.W    GD_font
    DC.L    0,0,0
    DC.W    342,58,55,13
    DC.L    setscreenText,0
    DC.W    GD_setscreen
    DC.L    PLACETEXT_IN,0,0
    DC.W    342,43,55,13
    DC.L    setfontText,0
    DC.W    GD_setfont
    DC.L    PLACETEXT_IN,0,0
    DC.W    25,62,26,11
    DC.L    overwriteText,0
    DC.W    GD_overwrite
    DC.L    PLACETEXT_RIGHT,0,0
    DC.W    206,58,133,13
    DC.L    0,0
    DC.W    GD_screen
    DC.L    0,0,0

Project0GTags:
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    GTCY_Labels,iconifyLabels
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    GTTX_Text,fontString
    DC.L    GTTX_Border,1
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    TAG_DONE
    DC.L    GTCY_Labels,screenLabels
    DC.L    TAG_DONE


fontString:
    DC.B    'Asphalt.14',0
    CNOP    0,2

displaypicText:
    DC.B    'Display Picture',0

Gadget10Text:
    DC.B    'drawgrid',0

autosavepalText:
    DC.B    'Autosave Pal.',0

confirmexitText:
    DC.B    'Confirm Exit',0

iconifyText:
    DC.B    'Iconify to',0

cancelText:
    DC.B    'Cancel',0

saveText:
    DC.B    'Save',0

useText:
    DC.B    'Use',0

adjustpalText:
    DC.B    'Adjust Palette',0

setscreenText:
    DC.B    'Set',0

setfontText:
    DC.B    'Font',0

overwriteText:
    DC.B    'Conf. Overwrite',0

    CNOP    0,2

    XDEF    iconifyLabels

iconifyLabels:
    DC.L    iconifyLab0
    DC.L    iconifyLab1
    DC.L    iconifyLab2
    DC.L    0

    XDEF    screenLabels

screenLabels:
    DC.L    screenLab0
    DC.L    screenLab1
    DC.L    screenLab2
    DC.L    0

iconifyLab0:    DC.B    'Toolmenu',0
iconifyLab1:    DC.B    'App Icon',0
iconifyLab2:    DC.B    'Window',0

    CNOP    0,2

screenLab0:    DC.B    'Workbench',0
screenLab1:    DC.B    'PublicScreen',0
screenLab2:    DC.B    'CustomScreen',0

    CNOP    0,2

    XDEF    topaz8

topaz8:
    DC.L    topazFName8
    DC.W    8
    DC.B    $00,$00

topazFName8:
    DC.B    'topaz.font',0
    CNOP    0,2

    XDEF    Project0WindowTags

Project0WindowTags:
Project0L:
    DC.L    WA_Left,0
Project0T:
    DC.L    WA_Top,0
Project0W:
    DC.L    WA_Width,0
Project0H:
    DC.L    WA_Height,0
    DC.L    WA_IDCMP,CHECKBOXIDCMP!CYCLEIDCMP!BUTTONIDCMP!TEXTIDCMP!IDCMP_GADGETDOWN!IDCMP_MOUSEMOVE!IDCMP_CLOSEWINDOW!IDCMP_REFRESHWINDOW
    DC.L    WA_Flags,WFLG_DRAGBAR!WFLG_DEPTHGADGET!WFLG_CLOSEGADGET!WFLG_SIZEBBOTTOM!WFLG_SMART_REFRESH
Project0WG:
    DC.L    WA_Gadgets,0
    DC.L    WA_Title,Project0WTitle
    DC.L    WA_ScreenTitle,Project0STitle
Project0SC:
    DC.L    WA_CustomScreen,0
    DC.L    TAG_DONE

Project0WTitle:
    DC.B    'ArtPRO Settings',0
    CNOP    0,2

Project0STitle:
    DC.B    'GadToolsBox V2.0b © 1991-1993',0
    CNOP    0,2

    XDEF    Project0Text0

Project0Text0:
    DC.B    2,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    280,12
    DC.L    topaz8
    DC.L    Project0IText0
    DC.L    Project0Text1

Project0Text1:
    DC.B    2,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    77,12
    DC.L    topaz8
    DC.L    Project0IText1
    DC.L    0

Project0IText0:
    DC.B    'System',0

Project0IText1:
    DC.B    'Global',0

    CNOP    0,2

DriPen:
    DC.W    $FFFF

    XDEF    ScreenTags

ScreenTags:
    DC.L    SA_Left,64
    DC.L    SA_Top,0
    DC.L    SA_Width,848
    DC.L    SA_Height,493
    DC.L    SA_Depth,3
    DC.L    SA_Font,topaz8
    DC.L    SA_Type,CUSTOMSCREEN
    DC.L    SA_DisplayID,DEFAULT_MONITOR_ID!SUPER_KEY
    DC.L    SA_Pens,DriPen
    DC.L    SA_Title,SCT
    DC.L    TAG_DONE

SCT:
    DC.B    'GadToolsBox V2.0b © 1991-1993',0
    CNOP    0,2

    XDEF    SetupScreen

SetupScreen
    movem.l d1-d3/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   ScreenTags,a1
    jsr     OpenScreenTagList(a6)
    move.l  d0,Scr
    tst.l   d0
    beq     SError
    move.l  Scr,a0
    move.l  _GadToolsBase,a6
    lea.l   TD,a1
    jsr     GetVisualInfoA(a6)
    move.l  d0,VisualInfo
    tst.l   d0
    beq     VError
    moveq   #0,d0
SDone:
    movem.l (sp)+,d1-d3/a0-a2/a6
    rts
SError:
    moveq   #1,d0
    bra.s   SDone
VError:
    moveq   #2,d0
    bra.s   SDone

    XDEF    CloseDownScreen

CloseDownScreen:
    movem.l d0-d1/a0-a1/a6,-(sp)
    move.l  _GadToolsBase,a6
    move.l  VisualInfo,a0
    cmpa.l  #0,a0
    beq.s   NoVis
    jsr     FreeVisualInfo(a6)
    move.l  #0,VisualInfo
NoVis:
    move.l  _IntuitionBase,a6
    move.l  Scr,a0
    cmpa.l  #0,a0
    beq.s   NoScr
    jsr     CloseScreen(a6)
    move.l  #0,Scr
NoScr:
    movem.l (sp)+,d0-d1/a0-a1/a6
    rts

    XDEF    Project0Render

Project0Render:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  Project0Wnd,a0
    move.b  wd_BorderLeft(a0),d4
    ext.w   d4
    move.b  wd_BorderTop(a0),d5
    ext.w   d5
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  Project0Wnd,a0
    move.l  wd_RPort(a0),a2
    move.l  a2,a0
    lea.l   NR,a1
    move.w  #195,d0
    add.w   d4,d0
    move.w  #23,d1
    add.w   d5,d1
    move.w  #212,d2
    move.w  #85,d3
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.w  #16,d0
    add.w   d4,d0
    move.w  #23,d1
    add.w   d5,d1
    move.w  #169,d2
    move.w  #85,d3
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.w  #14,d0
    add.w   d4,d0
    move.w  #22,d1
    add.w   d5,d1
    move.w  #173,d2
    move.w  #87,d3
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.w  #193,d0
    add.w   d4,d0
    move.w  #22,d1
    add.w   d5,d1
    move.w  #216,d2
    move.w  #87,d3
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.w  #7,d0
    add.w   d4,d0
    move.w  #5,d1
    add.w   d5,d1
    move.w  #410,d2
    move.w  #124,d3
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.w  #5,d0
    add.w   d4,d0
    move.w  #4,d1
    add.w   d5,d1
    move.w  #414,d2
    move.w  #126,d3
    jsr     DrawBevelBoxA(a6)
    move.l  _IntuitionBase,a6
    move.l  Project0Wnd,a0
    move.l  wd_RPort(a0),a0
    lea.l   Project0Text0,a1
    move.l  d4,d0
    move.l  d5,d1
    jsr     PrintIText(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenProject0Window

OpenProject0Window:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.b  sc_WBorLeft(a0),d2
    move.l  sc_Font(a0),a1
    move.w  ta_YSize(a1),d3
    addq.w  #1,d3
    move.b  sc_WBorTop(a0),d0
    ext.w   d0
    add.w   d0,d3
    move.l  _GadToolsBase,a6
    lea.l   Project0GList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     Project0CError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   Project0GTags,a4
Project0GL:
    move.l  _SysBase,a6
    lea.l   Project0NGads,a0
    move.l  d3,d0
    mulu    #gng_SIZEOF,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #gng_SIZEOF,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,gng_VisualInfo(a0)
    move.l  #topaz8,gng_TextAttr(a0)
    move.w  gng_LeftEdge(a0),d0
    add.w   (sp),d0
    move.w  d0,gng_LeftEdge(a0)
    move.w  gng_TopEdge(a0),d0
    add.w   2(sp),d0
    move.w  d0,gng_TopEdge(a0)
    move.l  _GadToolsBase,a6
    lea.l   Project0GTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    Project0COK
    movem.w (sp)+,d2-d3
    bra     Project0GError
Project0COK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   Project0Gadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
Project0TL:
    tst.l   (a4)
    beq.s   Project0DN
    addq.w  #8,a4
    bra.s   Project0TL
Project0DN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #Project0_CNT,d3
    bmi     Project0GL
    movem.w (sp)+,d2-d3
    move.l  Project0GList,Project0WG+4
    move.l  Scr,Project0SC+4
    moveq   #0,d0
    move.w  Project0Left,d0
    move.l  d0,Project0L+4
    move.w  Project0Top,d0
    move.l  d0,Project0T+4
    move.w  Project0Width,d0
    move.l  d0,Project0W+4
    move.w  Project0Height,d0
    add.w   d3,d0
    move.l  d0,Project0H+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   Project0WindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,Project0Wnd
    tst.l   d0
    beq     Project0WError
    move.l  _GadToolsBase,a6
    move.l  Project0Wnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    jsr     Project0Render
    moveq   #0,d0
Project0Done:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
Project0CError:
    moveq   #1,d0
    bra.s   Project0Done
Project0GError:
    moveq   #2,d0
    bra.s   Project0Done
Project0WError:
    moveq   #4,d0
    bra.s   Project0Done

    XDEF    CloseProject0Window

CloseProject0Window:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  Project0Wnd,a0
    cmpa.l  #0,a0
    beq     Project0NWnd
    jsr     CloseWindow(a6)
    move.l  #0,Project0Wnd
Project0NWnd:
    move.l  _GadToolsBase,a6
    move.l  Project0GList,a0
    cmpa.l  #0,a0
    beq     Project0NGad
    jsr     FreeGadgets(a6)
    move.l  #0,Project0GList
Project0NGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts


    end
